#!/bin/sh
#
# Start klipper service.
#

if [ "$(id -u)" -eq 0 ]; then
      su -c "$0 $@" creality
      exit 0
fi

product="`get_sn_mac.sh hostname | awk -F '-' '{print tolower($1)}'`"
if [ "$product" ]; then
    MODEL="$product-x2600"
else
    MODEL="k1c-x2600"
fi

USER_DATA=/usr/data
PROG=/usr/share/klippy-env/bin/python
DEFAULT_CFG=/usr/share/klipper/config/$MODEL
PRINTER_DATA_DIR=$USER_DATA/printer_data
PRINTER_CONFIG_DIR=$PRINTER_DATA_DIR/config
PRINTER_LOGS_DIR=$PRINTER_DATA_DIR/logs
SAMPLE_GCODE_DIR=/usr/share/klipper/gcodes
GCODE_FILES_DIR=$PRINTER_DATA_DIR/gcodes
PID_FILE=/home/creality/run/klippy.pid
PY_SCRIPT=/usr/share/klipper/klippy/klippy.py
if [ ! -f $PY_SCRIPT ]; then
    PY_SCRIPT=/usr/share/klipper/klippy/klippy.pyc
fi

get_cfg_version()
{
    local cfg="$1"
    local version=$(head "$cfg" | grep -w Version | awk '{print $3}')
    local tmp=""

    if [ "x$version" != "x" ]; then
        # remove char '.'
        tmp=${version//./}
        # remove char 'v' or 'V'
        tmp=${tmp//v/}
        version=${tmp//V/}
        echo "$version"
    else
        echo "000"
    fi
}

# Max backup cfg file count: 5
# file name like : printer.cfg.1, printer.cfg.2
backup_usr_cfg()
{
    local usr_cfg=$1

    if [ -f $usr_cfg ]; then
        count=$(ls $usr_cfg* | wc -l)
        i=$count
        while [ $i -ge 1 ]; do
            if [ $i -ge 6 ]; then
                echo "do nothing"
            elif [ $i -eq 1 ]; then
                cp $usr_cfg $usr_cfg.1 && sync
            else
                cp $usr_cfg.$((i-1)) $usr_cfg.$i && sync
            fi
            let i-=1
        done
    fi
}

update_config()
{
    local old_cfg="$2"
    local new_cfg="$1"
    local tmp_cfg=$PRINTER_CONFIG_DIR/.printer.cfg

    local old_version=$(get_cfg_version "$old_cfg")
    local new_version=$(get_cfg_version "$new_cfg")
    echo "old_version: $old_version"
    echo "new_version: $new_version"

    if [ $new_version -ne $old_version ]; then
        echo "backup user config"
        backup_usr_cfg "$old_cfg"
        echo "update config"
        cp "$new_cfg" "$tmp_cfg"
        echo "" >> "$tmp_cfg"
        cat "$old_cfg" | sed -n '/SAVE_CONFIG/,$p' >> "$tmp_cfg"
        cp "$tmp_cfg" "$old_cfg" && sync
        ls "${CONFIG_PATH}"/*.* | grep -v printer.cfg | xargs -I {} cp -af {} $PRINTER_CONFIG_DIR/
        sync
    fi
}

copy_config()
{
    CONFIG_PATH=$DEFAULT_CFG

    [ -d "${CONFIG_PATH}" ] || {
        echo "config_dir is not exist!"
        exit 0
    }

    if [ -s $PRINTER_CONFIG_DIR/printer.cfg ]; then
        # keep printer.cfg
        # ls "${CONFIG_PATH}"/*.* | grep -v printer.cfg | xargs -I {} cp -af {} $PRINTER_CONFIG_DIR/
        # sync

        # update printer.cfg and keep SAVE_CONFIG section
        update_config "$CONFIG_PATH/printer.cfg" $PRINTER_CONFIG_DIR/printer.cfg
    else
        cp -af "${CONFIG_PATH}"/* $PRINTER_CONFIG_DIR/
        sync
    fi
}

start() {
      [ -d $PRINTER_DATA_DIR ] || mkdir -p $PRINTER_DATA_DIR
      [ -d $PRINTER_CONFIG_DIR ] || mkdir -p $PRINTER_CONFIG_DIR
      [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR
      [ -d $GCODE_FILES_DIR ] || cp -rf $SAMPLE_GCODE_DIR $GCODE_FILES_DIR
      [ -d $GCODE_FILES_DIR ] || mkdir -p $GCODE_FILES_DIR
      [ -s $PRINTER_CONFIG_DIR/printer.cfg ] || cp -rf $DEFAULT_CFG/* $PRINTER_CONFIG_DIR/

      copy_config

      HOME=/root start-stop-daemon -S -q -b -m -p $PID_FILE \
            --exec $PROG -- $PY_SCRIPT \
            $PRINTER_CONFIG_DIR/printer.cfg \
            -l $PRINTER_LOGS_DIR/klippy.log \
            -a /tmp/klippy_uds
}
stop() {
        start-stop-daemon -K -q -p $PID_FILE
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
