#!/bin/sh
#

if [ "$(id -u)" -ne 0 ]; then
      echo "$0: Operation permission not permitted"
      exit 1
fi

case "$1" in
  start)
  	SN=$(get_sn_mac.sh board)
  	if [ -n "$SN" ]; then
  		echo "$SN" > /etc/hardware
  	else
  		echo "Failed to retrieve SN from get_sn_mac.sh" > /dev/kmsg
  	fi
  	
  	
	cd /module_driver/
	./driver_default_init_script.sh
	cd -
	;;
  *)
	exit 1
esac

exit $?
