#!/bin/sh
#
# Start bluetooth ....
#

if [ "$(id -u)" -ne 0 ]; then
      echo "$0: Operation permission not permitted"
      exit 1
fi

case "$1" in
  start)
    echo "Starting bluetooth ..."
    /usr/bin/bt_enable_aic.sh &
    ;;
  stop)
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
